
###########################################################################
################################  27/12/2002  #############################
############################  badwords.tcl  v1.0  ###################
###########################################################################
### 		Author: 	sMug	(Jérôme Fafchamps)		    		      ###
### 		IRC:						                                  ###
###########################################################################
#####################################################################
## Configuration du Script ##########################################
#####################################################################
#
#Licence d'utilisation libre :
#
#Ce script est fourni tel quel, sans garantie d'aucune sorte, expresse ou implicite. L'auteur ne peut en aucun cas être tenu responsable #de tout dommage résultant de l'utilisation de ce script.
#
#Cependant, l'auteur espère que ce script sera utile à d'autres utilisateurs et contribuera à améliorer leurs expériences avec Eggdrop.
#
#En utilisant ce script, vous acceptez ces termes de licence.


# Pour chaque channel à protéger, définir les mots interdits :

set badwords(#quizz) {
   "*fuck*"
   "vive*le*pen*"
   "*net*france*"
   "*vrai*fau*"
   "*fau*vrai*"
   "*1*2*3*4*5*6*7*8*9*10*"
   "*11*12*13*14*15*16*17*"
   "*18*19*20*21*22*23*24*25*"
   "*26*27*28*29*30*31*32*"
   "*33*34*35*36*37*38*39*"
   "*40*41*42*43*44*45*"
   "*46*47*48*49*50*51*"
   "*52*53*54*55*56*57*"
   "*58*59*60*61*62*63*"
   "*64*65*66*67*68*69*"
   "*70*71*72*73*74*75*"
   "*76*77*78*79*80*"
   "*81*82*83*84*85*86*"
   "*87*88*89*90*91*92*93*"
   "*94*95*96*97*98*99*"
   "*100*101*102*103*104*105*"
   "*106*107*108*109*110*"
   "*comalgerie*"
   "*encul*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "*gros*lard*"
   "*gross*merd*"
   "*bougnoule*"
   "*#*"
   "* pute*"
   "*www.*"
   "*http*"
   "*server -m*"
   "*ftp://*"
   "* tamer*"
   "*connard*"
   "*conar*"
   "*sal*noir*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*ta gueule*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suces*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux*"
   "*couille*"
   "*salope *"
   "*va baiser ta*"
   "*faire sucer*"
   }

set badwords(#francophonie) {
   "*fuck*"
   "*irc.*"
   "vive*le*pen*"
   "*encul*"
   "* Cons *"
   "*comalgerie*"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"
   "*gros*lard*"
   "*bougnoule*"
   "*sal*maracain*"
   "* pute*"
   "*encul*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*sal*noir*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*sperme*"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }

set badwords(#moinsde18ans) {
   "*fuck*"
   "*irc.*"
   "vive*le*pen*"
   "*comalgerie*"
   "*encul*"
   "* Cons *"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"
   "*gros*lard*"
   "*bougnoule*"
   "*sal*arabe*"
   "*sal*maracain*"
   "* pute*"
   "*encul*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*sal*noir*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*sperme*"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }

set badwords(#plusde18ans) {
   "*fuck*"
   "*irc.*"
   "vive*le*pen*"
   "*encul*"
   *comalgerie*"
   "* Cons *"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"
   "*gros*lard*"
   "*bougnoule*"
   "*sal*arabe*"
   "*sal*maracain*"
   "* pute*"
   "*encul*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*sal*noir*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*sperme*"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }

set badwords(#maghreb) {
   "*fuck*"
   "*irc.*"
   "*comalgerie*"
   "vive*le*pen*"
   "*encul*"
   "* Cons *"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"
   "*gros*lard*"
   "*bougnoule*"
   "* pute*"
   "*encul*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*sperme*"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }

set badwords(#radio) {
   "*fuck*"
   "*irc.*"
   "vive*le*pen*"
   "*encul*"
   "* Cons *"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"
   "*gros*lard*"
   "*bougnoule*"
   "* pute*"
   "*encul*"
   "*sperme*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }


set badwords(#moinsde18ans) {
   "*fuck*"
   "*irc.*"
   "vive*le*pen*"
   "*encul*"
   "* Cons *"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"
   "*gros*lard*"
   "*bougnoule*"
   "* pute*"
   "*encul*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*sperme*"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }

set badwords(#maghreb) {
   "*fuck*"
"* kahba*"
"* qahba*"
"* 3atay*"
"* 3attay*"
"* atay *"
"* nokch*"
"* kerfa*"
"* karfa*"
"* zamel*"
"* nik *"
"* nik mok*"
"* nique mok*"
"* tiz *"
"* souwa*"
"* soua*"
"* zab *"
"* zeb *"
"* ka3 *"
"* nyak*"
"* niyak*"
"* anafal*"
"* aghyoul*"
"* agouna*"
"* ateye*"
"* 9lawi*"
"* 9laoui*"
"* 9alwa*"
"*nadin bebek*"
"*emchi kawed*"
"*nikoumouk*"
"* kehba*"
"* bagraa*"
"* renza*"
"* hagouna*"
"* hmala*"
"*belagoumouk*"
"*nikoumouk*"
"*nahdilemouk*"
"*nahdilebabak*"
"*seni sikerim*"
"*balafamouk*"
"* miboun*"
"* asba *"
"* zok omek"
"* nik omek*"
"* tahene*"
	"*Artail ateye*"
   "*encul*"
   "* Cons *"
   "*comalgerie*"
   "*Grosse*merd*"
   "*fil*pute*"
   "*te*baise*"
   "*faire foutre*"
   "*faire baiser*"
   "* puta*"
   "* sexe *"                                                                               
   "*sal*arabe*"
   "*sal*maracain*"
   "* pute*"
   "*encul*"
   "*connard*"
   "*conar*"
   "*fils*pute*"
   "*bougnoume*"
   "*sal*noir*"
   "*arabe*merde*"
   "*enfoir*"
   "*abruti*"
   "*salaud*"
   "*stupide*"
   "*connasse*"
   "*branle*"
   "*bouffon*"
   "*boufon*"
   "*baise ta*"
   "*baise ton*"
   "*sodomise*"
   "*venez sur*"
   "* nique *"
   "* bite *"
   "* pd *"
   "*sperme*"
   "*ta gueule*"
   "*server -m*"
   "* tamer*"
   "*j*envi*sex*"
   "* suce *"
   "* tu suce*"
   "*salop*"
   "* cons *"
   "*pucel*"
   "*suceu*"
   "*sux *"
   "*couille*"
   "*va baiser ta mere*"
   "*faire sucer*"
   }

   
# Bannir après l'exclusion en minutes (-1=non, 0=noexpire) :
set badwords(bantime) 30

# Nombre d'avertissement avant l'exclusion (0=exclusion directe) :
set badwords(adv) 1
 
# Message du Kick :
set badwords(kickmsg) "Votre comportement est totalement contraire aux valeurs du chat"

# Laisser faire les utilisateurs ayant certains flags :
set badwords(ignflags) "fmnov|fmnov"

bind pubm -|- * badwords:pub
bind ctcp -|- ACTION badwords:action
bind notc -|- NOTICE badwords:notice

proc badwords:pub {nick uhost hand channel arg} {
global botnick badwords badwinc
set channel [string tolower $channel]
if {[info exists badwords($channel)] && (![matchattr $hand $badwords(ignflags) $channel]) && (![matchattr $hand b]) && ($nick != $botnick)} {
   set arg [string tolower $arg]
 if {([isvoice $nick $channel])} {return 0}
  if {([isop $nick $channel])} {return 0}  
  if {([ishalfop $nick $channel])} {return 0}  
if [botisop $channel] {
      foreach badword $badwords($channel) {
         if {[string match $badword $arg]} {
            if {[info exists badwinc($nick-$channel)]} {
               incr badwinc($nick-$channel) 1
               if {$badwinc($nick-$channel) >= $badwords(adv)} {
                  if {$badwords(bantime) != -1} {
                   #  newchanban $channel *!*[string range $uhost [string first "@" $uhost] end] $botnick "N'utilisez pas $badword sur ce canal!" $badwords(bantime)
                  putserv "MODE $channel +b *!*[string range $uhost [string first "@" $uhost] end]"
                  }
                  putserv "KICK $channel $nick :$badwords(kickmsg)"
                  dccbroadcast "Attention : Mot interdit détecté ($badword) sur $channel by $nick ($uhost)"
                  unset badwinc($nick-$channel)
                  return 1
               }
            } elseif $badwords(adv) {
               putserv "KICK $channel $nick :N'utilisez pas l'expression $badword sur ce canal! "
               dccbroadcast "Attention : Mot interdit détecté ($badword) sur $channel by $nick ($uhost)"             
               set badwinc($nick-$channel) 0
               return 1
            } else {
               if {$badwords(bantime) != -1} {
               #  newchanban $channel *!*[string range $uhost [string first "@" $uhost] end] $botnick "Pas de $badword sur $channel , je t'ai prevenu tu es banni ..." $badwords(bantime)  
                 putserv "MODE $channel +b *!*[string range $uhost [string first "@" $uhost] end]"
                 }
               putserv "KICK $channel $nick :$badwords(kickmsg)"
               dccbroadcast "Attention : Mot interdit détecté ($badword) sur $channel by $nick ($uhost)"             
               unset badwinc($nick-$channel)
               return 1
            }
         }
      }
      return 1
   }
}
}

proc badwords:action {nick uhost hand channel key arg} {
badwords:pub $nick $uhost $hand $channel $arg
}

proc badwords:notice {from key arg} {
if {[string index [lindex $arg 0] 0] == "#"} {
   set nick [string range $from 0 [expr [string first "!" $from]-1]]
   set uhost [string range $from [expr [string first "!" $from]+1] e]
   set channel [lindex [lindex $arg 0] 0]
   set hand [nick2hand $nick $channel]
   set arg "\{[string trimright [string range $arg [expr [string first ":" $arg]+1] e] \}]\}"
   badwords:pub $nick $uhost $hand $channel $arg
}
return 0
}

putlog "Espace-IRC - BadWords v1.0 by sMug Chargé"
